name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install gcc and so on
        run: |
          apt install gcc libc6-dev
          apt install libx11-dev xorg-dev libxtst-dev libpng++-dev
          apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
          apt install libxkbcommon-dev
          apt install xsel xclip

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -x ./
